[package]
name = "fvm-workbench-vm"
description = "Standalone Filecoin virtual machine for development, testing, and debugging"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["@anorth"]
edition = "2021"

[dependencies]
fvm-workbench-api = { path = "../api" }

# fvm feature=testing required to not be amazingly slow
fvm = { version = "2.1.0", default-features = false, features = ["testing"] }
fvm_shared = { version = "2.0.0" }
fvm_ipld_hamt = { version = "~0.5.1"}
fvm_ipld_amt = { version = "~0.4.2"}
fvm_ipld_car = { version = "~0.5.0"}
fvm_ipld_blockstore = { version = "~0.1.1"}
fvm_ipld_encoding = { version = "~0.2.2"}

anyhow = "~1.0.47"
cid = { version = "~0.8.5", default-features = false }
futures = "~0.3.19"
multihash = { version = "~0.16.1", default-features = false }
thiserror = "~1.0.30"
