[package]
name = "fvm-workbench-builtin-actors"
description = "FVM workbench instance with built-in actors"
version = "0.1.0"
license = "MIT OR Apache-2.0"
authors = ["@anorth"]
edition = "2021"

[dependencies]
fvm-workbench-vm = { path = "../vm" }
fvm-workbench-api = { path = "../api" }

actors-v10 = { package = "fil_builtin_actors_bundle", version = "10.0.0-alpha.1", git = "https://github.com/filecoin-project/builtin-actors", rev = "d2924bfd" }
fil_actor_account = { version = "10.0.0-alpha.1", git = "https://github.com/filecoin-project/builtin-actors", rev = "d2924bfd", features = [] }
fil_actor_cron = { version = "10.0.0-alpha.1", git = "https://github.com/filecoin-project/builtin-actors", rev = "d2924bfd", features = [] }
fil_actor_datacap = { version = "10.0.0-alpha.1", git = "https://github.com/filecoin-project/builtin-actors", rev = "d2924bfd", features = [] }
fil_actor_init = { version = "10.0.0-alpha.1", git = "https://github.com/filecoin-project/builtin-actors", rev = "d2924bfd", features = [] }
fil_actor_market = { version = "10.0.0-alpha.1", git = "https://github.com/filecoin-project/builtin-actors", rev = "d2924bfd", features = [] }
fil_actor_miner = { version = "10.0.0-alpha.1", git = "https://github.com/filecoin-project/builtin-actors", rev = "d2924bfd", features = [] }
fil_actor_multisig = { version = "10.0.0-alpha.1", git = "https://github.com/filecoin-project/builtin-actors", rev = "d2924bfd", features = [] }
fil_actor_paych = { version = "10.0.0-alpha.1", git = "https://github.com/filecoin-project/builtin-actors", rev = "d2924bfd", features = [] }
fil_actor_power = { version = "10.0.0-alpha.1", git = "https://github.com/filecoin-project/builtin-actors", rev = "d2924bfd", features = [] }
fil_actor_reward = { version = "10.0.0-alpha.1", git = "https://github.com/filecoin-project/builtin-actors", rev = "d2924bfd", features = [] }
fil_actor_system = { version = "10.0.0-alpha.1", git = "https://github.com/filecoin-project/builtin-actors", rev = "d2924bfd", features = [] }
fil_actor_verifreg = { version = "10.0.0-alpha.1", git = "https://github.com/filecoin-project/builtin-actors", rev = "d2924bfd", features = [] }
fil_actors_runtime = { version = "10.0.0-alpha.1", git = "https://github.com/filecoin-project/builtin-actors", rev = "d2924bfd", features = [] }

fvm = { version = "2.1.0", default-features = false, features = ["testing"] }
fvm_shared = { version = "2.0.0" }
fvm_ipld_hamt = { version = "~0.5.1"}
fvm_ipld_amt = { version = "~0.4.2"}
fvm_ipld_car = { version = "~0.5.0"}
fvm_ipld_blockstore = { version = "~0.1.1"}
fvm_ipld_encoding = { version = "~0.2.2"}

# Used directly in some tests
frc46_token = "~3.1.0"

anyhow = "~1.0.47"
cid = { version = "~0.8.5", default-features = false }
multihash = { version = "~0.16.1", default-features = false }
rand_chacha = "~0.3"
thiserror = "~1.0.30"
