name: Benchmark builtin actors

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  benchmark-builtins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run builtin-actors' integration tests
        run: make benchmark
